#! /usr/bin/perl -w
# $Id: $
#
# SYNOPSIS
#     prepare_pod Module.pm > Module.pm.new
#
# DESCRIPTION
#
# A simple filter to prepare XIMS modules with JavaDoc-style comments
# for the change to POD.
#
# BUGS AND LIMITATION
#
# It's just a simple, stupid script.
#
# runnig perldoc on it doesn't show anything useful :-)
#
# LICENCE AND COPYRIGHT
#
# Copyright (c) 2002-2007 The XIMS Project.
#
# See the file "LICENSE" for information and conditions for use,
# reproduction, and distribution of this work, and for a DISCLAIMER OF ALL
# WARRANTIES.

use strict;

my $package;
my $in_module_section = 0;
my $kill_indent;
my $code_fixed;

while (<>) {

    if (/package\s+([A-Za-z_:]+)\s*;/m) {
        $package = $1;
    }

    if (/^##/) {
        $in_module_section = 1;
    }

    if ( !/^#/ && $in_module_section == 1 ) {
        $code_fixed .= "=cut\n\n";
        $in_module_section = 0;
    }

    if ($in_module_section) {
        $kill_indent = 0 if s/^##.*//m;
        $kill_indent = 0 if s/^#\s+SYNOPSIS.*\n/=head2/;
        $kill_indent = 0 if s/^#\s+PARAMETERS?/=head3 Parameter\n/;
        $kill_indent = 0
            if s/^#\s+(?:RETURNS|RETURN\s*VALUES)/=head3 Returns\n/;
        $kill_indent = 1 if s/^#\s+DESCRIPTION/=head3 Description\n/;
        $kill_indent = 1 if s/^#\s+EXAMPLE/=head3 Example\n/;
        $kill_indent = 1
            if s/^#\s+GENERAL/=head2 Please put me somewhere else\n/;

        if ( $kill_indent == 1 ) {
            s/^# *//m;
        }
        else {
            s/^#//m;
        }
    }

    # remove old copyright and svn tag
    s/# Copyright .*\n//;
    s/# See the file "LICENSE" .*\n//;
    s/# and distribution of .*\n//;
    s/# \$Id:.*\$.*\n//;

    $code_fixed .= "$_";
}

print << "EOPREFIX";

=head1 NAME

$package -- A .... doing bla, bla, bla. (short)

=head1 VERSION

\$Id:\$

=head1 SYNOPSIS

    use $package;

=head1 DESCRIPTION

This module bla bla

=head1 SUBROUTINES/METHODS

=cut

EOPREFIX

print $code_fixed;

print << "EOPOSTFIX";

__END__

=head1 DIAGNOSTICS

Look at the F<error_log> file for messages.

=head1 CONFIGURATION AND ENVIRONMENT

in F<httpd.conf>: yadda, yadda...

Optional section , remove if bogus

=head1 DEPENDENCIES

Optional section, remove if bogus.

=head1 INCOMPATABILITIES

Optional section, remove if bogus.

=head1 BUGS AND LIMITATION

Grep the source file for: XXX, TODO, ITS_A_HACK_ALARM.

=head1 LICENCE AND COPYRIGHT

Copyright (c) 2002-2007 The XIMS Project.

See the file F<LICENSE> for information and conditions for use, reproduction,
and distribution of this work, and for a DISCLAIMER OF ALL WARRANTIES.

=cut

# Local Variables:
#   mode: cperl
#   cperl-indent-level: 4
#   cperl-close-paren-offset: -4
#   cperl-continued-statement-offset: 4
#   cperl-indent-level: 4
#   cperl-indent-parens-as-block: t
#   cperl-merge-trailing-else: nil
#   cperl-tab-always-indent: t
#   fill-column: 78
#   indent-tabs-mode: nil
# End:
# ex: set ts=4 sr sw=4 tw=78 ft=perl et :

EOPOSTFIX

__END__

# Local Variables:
#   mode: cperl
#   cperl-indent-level: 4
#   cperl-close-paren-offset: -4
#   cperl-continued-statement-offset: 4
#   cperl-indent-level: 4
#   cperl-indent-parens-as-block: t
#   cperl-merge-trailing-else: nil
#   cperl-tab-always-indent: t
#   fill-column: 78
#   indent-tabs-mode: nil
# End:
# ex: set ts=4 sr sw=4 tw=78 ft=perl et :
