PROMPT Dropping Foreign Key 'CTT_DOC_STYLE_FK'
ALTER TABLE CI_CONTENT DROP CONSTRAINT
 CTT_DOC_STYLE_FK
/

PROMPT Dropping Foreign Key 'CTT_DOC_CSS_FK'
ALTER TABLE CI_CONTENT DROP CONSTRAINT
 CTT_DOC_CSS_FK
/

PROMPT Dropping Foreign Key 'CTT_DOC_IMAGE_FK'
ALTER TABLE CI_CONTENT DROP CONSTRAINT
 CTT_DOC_IMAGE_FK
/

PROMPT Dropping Foreign Key 'CTT_DOC_SCRIPT_FK'
ALTER TABLE CI_CONTENT DROP CONSTRAINT
 CTT_DOC_SCRIPT_FK
/

PROMPT Creating Foreign Key 'CTT_CTT_STYLE_FK'
ALTER TABLE CI_CONTENT ADD (CONSTRAINT
 CTT_CTT_STYLE_FK FOREIGN KEY
  (STYLE_ID) REFERENCES CI_CONTENT
  (ID))
/

PROMPT Creating Foreign Key 'CTT_CTT_CSS_FK'
ALTER TABLE CI_CONTENT ADD (CONSTRAINT
 CTT_CTT_CSS_FK FOREIGN KEY
  (CSS_ID) REFERENCES CI_CONTENT
  (ID))
/

PROMPT Creating Foreign Key 'CTT_CTT_IMAGE_FK'
ALTER TABLE CI_CONTENT ADD (CONSTRAINT
 CTT_CTT_IMAGE_FK FOREIGN KEY
  (IMAGE_ID) REFERENCES CI_CONTENT
  (ID))
/

PROMPT Creating Foreign Key 'CTT_CTT_SCRIPT_FK'
ALTER TABLE CI_CONTENT ADD (CONSTRAINT
 CTT_CTT_SCRIPT_FK FOREIGN KEY
  (SCRIPT_ID) REFERENCES CI_CONTENT
  (ID))
/
