#!/bin/bash
# This is just a starting point/example, adapt to your needs.
export XIMS_HOME=/opt/xims
export PERLBREW_ROOT=/opt/perl5
export PERLBREW_HOME=/tmp/.perlbrew
source ${PERLBREW_ROOT}/etc/bashrc
#source db.env
#export DBI_TRACE=1

perlbrew use 5.16.3

cd "${XIMS_HOME}/lib"

WORKERS=12
LOG_DIR=${XIMS_HOME}/logs
PID_FILE=${LOG_DIR}/pid
STATUS_FILE=${LOG_DIR}/status
PORT=172.0.0.1:5000
GROUP=nobody
USER=nobody

OPTIONS="--port ${PORT} --pid-file=${PID_FILE} --interval=5 --status-file=${STATUS_FILE} --signal-on-hup=QUIT --\
                             starman --workers ${WORKERS} --user ${USER} --group ${GROUP} --access-log ${LOG_DIR}/access_log --error-log ${LOG_DIR}/error_log"

case "$1" in 
	start)
	        start_server ${OPTIONS} --preload-app xims.psgi >> ${LOG_DIR}/error_log 2>&1 &
        ;;
        restart)
	        start_server --restart ${OPTIONS} --
	;;
        stop)
                [[ -e ${PID_FILE} ]] && kill `cat ${PID_FILE}` || echo "Sorry, I cannot find the PID file, is the server still running?"
        ;;
	debug)
                exec plackup -R . --port 5000 xims.psgi  >> ${LOG_DIR}/error_log 2>&1
        ;;
    *)
        	echo "Usage: $0 [start|restart|stop|debug]"
        	exit 1
esac

