-- Copyright (c) 2002-2003 The XIMS Project.
-- See the file "LICENSE" for information on usage and redistribution
-- of this file, and for a DISCLAIMER OF ALL WARRANTIES.
-- $Id$
/*
 *
 * The XIMS Test Suite
 *
 *
*/

INSERT INTO CI_DOCUMENTS (LOCATION,STATUS,ID,PARENT_ID,OBJECT_TYPE_ID,DEPARTMENT_ID,DATA_FORMAT_ID,SYMNAME_TO_DOC_ID,POSITION) VALUES ('testsuite',NULL,3,1,5,1,18,NULL,2);
INSERT INTO CI_DOCUMENTS (LOCATION,STATUS,ID,PARENT_ID,OBJECT_TYPE_ID,DEPARTMENT_ID,DATA_FORMAT_ID,SYMNAME_TO_DOC_ID,POSITION) VALUES ('document.html',NULL,4,3,1,3,2,NULL,1);
INSERT INTO CI_DOCUMENTS (LOCATION,STATUS,ID,PARENT_ID,OBJECT_TYPE_ID,DEPARTMENT_ID,DATA_FORMAT_ID,SYMNAME_TO_DOC_ID,POSITION) VALUES ('folder',NULL,5,3,4,3,18,NULL,2);
INSERT INTO CI_DOCUMENTS (LOCATION,STATUS,ID,PARENT_ID,OBJECT_TYPE_ID,DEPARTMENT_ID,DATA_FORMAT_ID,SYMNAME_TO_DOC_ID,POSITION) VALUES ('file.zip',NULL,6,3,6,3,16,NULL,3);
INSERT INTO CI_DOCUMENTS (LOCATION,STATUS,ID,PARENT_ID,OBJECT_TYPE_ID,DEPARTMENT_ID,DATA_FORMAT_ID,SYMNAME_TO_DOC_ID,POSITION) VALUES ('xslstylesheet.xsl',NULL,7,3,8,1,3,NULL,5);
INSERT INTO CI_DOCUMENTS (LOCATION,STATUS,ID,PARENT_ID,OBJECT_TYPE_ID,DEPARTMENT_ID,DATA_FORMAT_ID,SYMNAME_TO_DOC_ID,POSITION) VALUES ('http://xims.uibk.ac.at/',NULL,8,3,13,1,22,NULL,6);
INSERT INTO CI_DOCUMENTS (LOCATION,STATUS,ID,PARENT_ID,OBJECT_TYPE_ID,DEPARTMENT_ID,DATA_FORMAT_ID,SYMNAME_TO_DOC_ID,POSITION) VALUES ('symboliclink',NULL,9,3,14,3,23,4,7);
INSERT INTO CI_DOCUMENTS (LOCATION,STATUS,ID,PARENT_ID,OBJECT_TYPE_ID,DEPARTMENT_ID,DATA_FORMAT_ID,SYMNAME_TO_DOC_ID,POSITION) VALUES ('axpointpresentation.axp',NULL,10,3,19,3,20,NULL,8);
INSERT INTO CI_DOCUMENTS (LOCATION,STATUS,ID,PARENT_ID,OBJECT_TYPE_ID,DEPARTMENT_ID,DATA_FORMAT_ID,SYMNAME_TO_DOC_ID,POSITION) VALUES ('image.png',NULL,11,3,20,3,15,NULL,9);
INSERT INTO CI_DOCUMENTS (LOCATION,STATUS,ID,PARENT_ID,OBJECT_TYPE_ID,DEPARTMENT_ID,DATA_FORMAT_ID,SYMNAME_TO_DOC_ID,POSITION) VALUES ('docbookxml.dkb',NULL,12,3,24,1,21,NULL,10);
