-- Copyright (c) 2002-2003 The XIMS Project.
-- See the file "LICENSE" for information on usage and redistribution
-- of this file, and for a DISCLAIMER OF ALL WARRANTIES.
-- $Id$
/*
 *
 * The XIMS Test Suite
 *
 *
 */

INSERT INTO CI_OBJECT_PRIVS_GRANTED (PRIVILEGE_MASK,GRANTEE_ID,GRANTOR_ID,CONTENT_ID) VALUES (1,1,2,2);
INSERT INTO CI_OBJECT_PRIVS_GRANTED (PRIVILEGE_MASK,GRANTEE_ID,GRANTOR_ID,CONTENT_ID) VALUES (1124151071,2,2,3);
INSERT INTO CI_OBJECT_PRIVS_GRANTED (PRIVILEGE_MASK,GRANTEE_ID,GRANTOR_ID,CONTENT_ID) VALUES (1124151071,2,2,4);
INSERT INTO CI_OBJECT_PRIVS_GRANTED (PRIVILEGE_MASK,GRANTEE_ID,GRANTOR_ID,CONTENT_ID) VALUES (1124151071,2,2,5);
INSERT INTO CI_OBJECT_PRIVS_GRANTED (PRIVILEGE_MASK,GRANTEE_ID,GRANTOR_ID,CONTENT_ID) VALUES (1124151071,2,2,6);
INSERT INTO CI_OBJECT_PRIVS_GRANTED (PRIVILEGE_MASK,GRANTEE_ID,GRANTOR_ID,CONTENT_ID) VALUES (1124151071,2,2,7);
INSERT INTO CI_OBJECT_PRIVS_GRANTED (PRIVILEGE_MASK,GRANTEE_ID,GRANTOR_ID,CONTENT_ID) VALUES (1124151071,2,2,8);
INSERT INTO CI_OBJECT_PRIVS_GRANTED (PRIVILEGE_MASK,GRANTEE_ID,GRANTOR_ID,CONTENT_ID) VALUES (1124151071,2,2,9);
INSERT INTO CI_OBJECT_PRIVS_GRANTED (PRIVILEGE_MASK,GRANTEE_ID,GRANTOR_ID,CONTENT_ID) VALUES (1124151071,2,2,10);
INSERT INTO CI_OBJECT_PRIVS_GRANTED (PRIVILEGE_MASK,GRANTEE_ID,GRANTOR_ID,CONTENT_ID) VALUES (1124151071,2,2,11);
INSERT INTO CI_OBJECT_PRIVS_GRANTED (PRIVILEGE_MASK,GRANTEE_ID,GRANTOR_ID,CONTENT_ID) VALUES (1124151071,2,2,12);
