PROMPT Adding IS_OBJECTROOT column on 'CI_OBJECT_TYPES'
ALTER TABLE ci_object_types ADD (IS_OBJECTROOT NUMBER(1,0) DEFAULT 0)
/

PROMPT Inserting new object type JavaScript
INSERT INTO CI_OBJECT_TYPES ( id, name, is_fs_container, is_xims_data, redir_to_self, publish_gopublic ) VALUES ( OBT_SEQ.NEXTVAL, 'JavaScript', 0, 1, 1, 0 )
/

INSERT INTO CI_MIME_TYPE_ALIASES ( id, data_format_id, mime_type ) VALUES ( MTA_SEQ.NEXTVAL, 16, 'application/zip' )
/

PROMPT Dropping Foreign Key 'CTT_DOC_STYLE_FK'
ALTER TABLE CI_CONTENT DROP CONSTRAINT
 CTT_DOC_STYLE_FK
/

PROMPT Dropping Foreign Key 'CTT_DOC_CSS_FK'
ALTER TABLE CI_CONTENT DROP CONSTRAINT
 CTT_DOC_CSS_FK
/

PROMPT Dropping Foreign Key 'CTT_DOC_IMAGE_FK'
ALTER TABLE CI_CONTENT DROP CONSTRAINT
 CTT_DOC_IMAGE_FK
/

PROMPT Dropping Foreign Key 'CTT_DOC_SCRIPT_FK'
ALTER TABLE CI_CONTENT DROP CONSTRAINT
 CTT_DOC_SCRIPT_FK
/

PROMPT Creating Foreign Key 'CTT_CTT_STYLE_FK'
ALTER TABLE CI_CONTENT ADD (CONSTRAINT
 CTT_CTT_STYLE_FK FOREIGN KEY
  (STYLE_ID) REFERENCES CI_CONTENT
  (ID))
/

PROMPT Creating Foreign Key 'CTT_CTT_CSS_FK'
ALTER TABLE CI_CONTENT ADD (CONSTRAINT
 CTT_CTT_CSS_FK FOREIGN KEY
  (CSS_ID) REFERENCES CI_CONTENT
  (ID))
/

PROMPT Creating Foreign Key 'CTT_CTT_IMAGE_FK'
ALTER TABLE CI_CONTENT ADD (CONSTRAINT
 CTT_CTT_IMAGE_FK FOREIGN KEY
  (IMAGE_ID) REFERENCES CI_CONTENT
  (ID))
/

PROMPT Creating Foreign Key 'CTT_CTT_SCRIPT_FK'
ALTER TABLE CI_CONTENT ADD (CONSTRAINT
 CTT_CTT_SCRIPT_FK FOREIGN KEY
  (SCRIPT_ID) REFERENCES CI_CONTENT
  (ID))
/
