-- Copyright (c) 2002-2005 The XIMS Project.
-- See the file "LICENSE" for information on usage and redistribution
-- of this file, and for a DISCLAIMER OF ALL WARRANTIES.
-- $Id$

-- DDL for additional columns
--
-- columns should be moved to ci_ddl.tab!

ALTER TABLE CI_CONTENT ADD (
        LOCKED_BY_LASTNAME VARCHAR2(90)
        , LOCKED_BY_MIDDLENAME VARCHAR2(30)
        , LOCKED_BY_FIRSTNAME VARCHAR2(90)
        , LAST_MODIFIED_BY_LASTNAME VARCHAR2(90)
        , LAST_MODIFIED_BY_MIDDLENAME VARCHAR2(30)
        , LAST_MODIFIED_BY_FIRSTNAME VARCHAR2(90)
        , OWNED_BY_LASTNAME VARCHAR2(90)
        , OWNED_BY_MIDDLENAME VARCHAR2(30)
        , OWNED_BY_FIRSTNAME VARCHAR2(90)
        , CREATED_BY_LASTNAME VARCHAR2(90)
        , CREATED_BY_MIDDLENAME VARCHAR2(30)
        , CREATED_BY_FIRSTNAME VARCHAR2(90)
        , LAST_PUBLISHED_BY_LASTNAME VARCHAR2(90)
        , LAST_PUBLISHED_BY_MIDDLENAME VARCHAR2(30)
        , LAST_PUBLISHED_BY_FIRSTNAME VARCHAR2(90)
        , DATA_FORMAT_NAME VARCHAR2(40)
)
/

